# Streamlit app configuration
page:
  title: "Translation History Dashboard"
  icon: "🌐"
  layout: "wide"

api:
  base_url: "http://localhost:8000/api/v1"
  timeout: 30
  cache_duration: 300

display:
  date_formats:
    short: "%Y-%m-%d"
    long: "%Y-%m-%d %H:%M:%S"
  chart_colors:
    primary: "#1f77b4"
    secondary: "#ff7f0e"
    accent: "#2ca02c"
  table_page_size: 20
  max_text_length: 100

filters:
  date_ranges:
    - "Last 7 days"
    - "Last 30 days"
    - "Last 90 days"
    - "Custom"
  default_confidence: 0.0
  sort_options:
    - "created_at"
    - "confidence_score"
    - "cost"
  export_formats:
    - "CSV"
    - "Excel"
    - "JSON"